"""Tests for the redesigned PoE2-style radial passive tree (generated by
tools/build_skill_tree.py) and its integrations: legacy id/adjacency contract,
scale, connectivity, keystone mapping, tree-granted resistances, and the
save-load auto-refund of orphaned allocations. ASCII-only output.
"""
import math
import os

os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
os.environ.setdefault("SDL_AUDIODRIVER", "dummy")

from src.spells.skill_tree import SkillTree
from src.spells.keystones import NODE_TO_KEYSTONE


def check(label, cond):
    assert cond, label


def test_tree_scale_and_tiers():
    t = SkillTree()
    check("tree is in the 250-350 node range", 250 <= len(t.nodes) <= 350)
    tiers = {}
    for n in t.nodes.values():
        tiers[n.tier] = tiers.get(n.tier, 0) + 1
    check("has plenty of minors", tiers.get("minor", 0) >= 180)
    check("has a healthy notable count", tiers.get("notable", 0) >= 20)
    check("has at least 8 keystones", tiers.get("keystone", 0) >= 8)


def test_tree_fully_connected():
    t = SkillTree()
    seen, stack = {"root"}, ["root"]
    while stack:
        for nb in t.nodes[stack.pop()].neighbors:
            if nb not in seen:
                seen.add(nb)
                stack.append(nb)
    check("every node reachable from root", seen == set(t.nodes))


def test_legacy_contract():
    t = SkillTree()
    for nid in ("fire_1", "fire_2", "fire_3", "fire_key", "mana_1", "mana_2",
                "mana_3", "dmg_1", "dmg_2", "dmg_3", "lightning_1", "speed_1",
                "atk_1", "atk_2", "atk_notable", "move_1", "move_2",
                "move_notable", "hpregen_notable", "hybrid_ld"):
        check(f"legacy node {nid} exists", nid in t.nodes)
    root_nb = set(t.nodes["root"].neighbors)
    for nid in ("fire_1", "mana_1", "dmg_1", "lightning_1", "speed_1"):
        check(f"{nid} adjacent to root", nid in root_nb)
    check("move_1 NOT adjacent to root (cut-vertex contract)",
          "move_1" not in root_nb)
    check("hybrid_ld bridges lightning_1",
          "lightning_1" in t.nodes["hybrid_ld"].neighbors)
    check("hybrid_ld bridges dmg_1", "dmg_1" in t.nodes["hybrid_ld"].neighbors)
    # Mechanical keystone nodes exist and carry the keystone tier.
    for nid in NODE_TO_KEYSTONE:
        check(f"keystone node {nid} exists", nid in t.nodes)
        check(f"keystone node {nid} has keystone tier",
              t.nodes[nid].tier == "keystone")


def test_no_overlapping_nodes():
    t = SkillTree()
    pts = [(n.x, n.y) for n in t.nodes.values()]
    for i in range(len(pts)):
        for j in range(i + 1, len(pts)):
            d = math.hypot(pts[i][0] - pts[j][0], pts[i][1] - pts[j][1])
            check("no two nodes overlap (>=30px apart)", d >= 30)


def test_region_labels_exported():
    from src.core.data_loader import load_json
    regions = load_json("skill_tree_regions.json")
    names = {r["name"] for r in regions}
    check("all six regions labelled", {
        "FIRE", "LIGHTNING", "SORCERY", "ALACRITY", "SUMMONING",
        "BLOOD & IRON", "WINTER"} <= names)


def test_tree_resistances_reach_player():
    from main import Game
    g = Game(900, 650)
    # Walk a path into the Blood region's Elements Ward wheel.
    path = ["blood_1", "bl_t1", "bl_t2", "bl_t3", "bl_rt"]
    for nid in path:
        check(f"allocate {nid}", g.skill_tree.allocate_node(nid))
    # Allocate the resistance wheel entry + notable.
    wheel_entry = next(n for n in g.skill_tree.nodes["bl_rt"].neighbors
                       if n.startswith("bl_wb"))
    check("allocate wheel entry", g.skill_tree.allocate_node(wheel_entry))
    fire_res_before = g.player.get_resistance("fire")
    g.recompute_player_stats()
    check("tree resistance nodes raise player resistance",
          g.player.get_resistance("fire") > fire_res_before)
    check("resistance stays capped at 75",
          g.player.get_resistance("fire") <= 75)


def test_save_load_refunds_orphaned_nodes():
    from main import Game
    from src.core import save as save_system

    g = Game(900, 650)
    g.player.skill_points = 5
    for nid in ("fire_1", "fire_2"):
        g.skill_tree.allocate_node(nid)
        g.player.skill_points -= 1

    data = save_system.build_save(g)
    # Simulate a save from an older tree revision: one id no longer exists.
    data["allocated_nodes"].append("ghost_node_from_old_tree")

    save_system.apply_save(g, data)
    check("known nodes reallocated",
          g.skill_tree.allocations["fire_1"] and g.skill_tree.allocations["fire_2"])
    check("orphaned node refunded as a skill point",
          g.player.skill_points == 3 + 1)
